contact_links:
    - name: 📶 HKMP Discord
      url: https://discord.gg/ggQdc9bP
      about: Ask questions about and host/join multiplayer Hollow Knight session.
      
    - name: 💬 Modding Discord
      url: https://discord.gg/VDsg3HmWuB
      about: Ask questions and talk about modding Hollow Knight with others.